### PR TITLE
Get user profile

### PR DESCRIPTION
**Pull request by anuveyatsu**
API for getting user profile information: `/auth/get_profile?username=<username>`

* new method `get_profile_by_username` in controllers
  * tests
* blueprint

### CODE REVIEW

**Comment by rufuspollock** [comment]
@anuveyatsu what issue does this relate to? Also what is the access restriction on this? And have you run it past @akariv ?

**Comment by akariv** [comment]
Hmm... not sure what this is going to be used for.
Anyway I don't think we'd like to expose the email address of all users via an api, no?

**Comment by anuveyatsu** [comment]
@akariv so probably we can expose some specific fields: username, userid, full name(?) and join_date. What do you think?

**Comment by akariv** [comment]
What's the purpose @anuveyatsu <https://github.com/anuveyatsu>?

**Comment by anuveyatsu** [comment]
@akariv In the frontend, we want to show user profile information such as joined_date (maybe some more in the future).

**Comment by akariv** [comment]
Okay - so yes, let's select exactly the fields that we want to expose publicly and only these should be returned in the API.

**Comment by anuveyatsu** [comment]
@akariv @rufuspollock so I will have these fields exposed:
* userid
* join_date

Please, confirm.

**Pull request merged**
